apiVersion: v1
kind: Secret
metadata:
  name: demo-weather-secrets
  labels:
    app: demo-weather
  annotations:
    forge.initializ.ai/generated: "true"
type: Opaque
stringData:
  # optional
  OPENAI_API_KEY: ""
